name: crud_example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  cupertino_icons: ^1.0.0
  http: ^0.12.0+2
  connectivity: ^2.0.2  
  shared_preferences: ^0.5.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
flutter:
  uses-material-design: true
